---
- name: Copy mongod replicaset initialize file
  template: src=sharding_conf.j2 dest=/tmp/sharding_conf.js
  sudo: yes

- name: Config mongodb sharding
  shell: /usr/bin/mongo 127.0.0.1:{{ mongos_port }}/admin /tmp/sharding_conf.js
